services:
  mongo:
    image: mongo:7
    container_name: mongo    

  mongo-express:
    image: mongo-express
    container_name: mongo-express    
    depends_on:
      - mongo

  backenddesafio.api:
    container_name: backenddesafio.api
    image: ${DOCKER_REGISTRY-}backenddesafioapi
    build:
      context: .
      dockerfile: src/BackendDesafio.API/Dockerfile
    depends_on:
      - mongo

volumes:
  mongo_data: